import Link from 'next/link';
import { getAllEarbuds, getBrands } from '@/lib/queries';
import { canonicalFor, JsonLd } from '@/lib/seo';
import { Footer } from '@/components/UI';

export const revalidate = 3600;
const n = (v) => Number.isFinite(Number(v)) ? Number(v) : null;
const price = (v) => n(v) == null ? '—' : `$${Math.round(n(v))}`;
const battery = (m) => n(m.battery_bud_h);
const totalBattery = (m) => n(m.battery_case_h) ?? n(m.battery_total_h);

function Card({ row, brand, locale }) {
  const { model, hours } = row;
  return <Link href={`/${locale}/ecouteurs/${model.id}`} className="block bg-panel border border-line rounded-2xl p-5 hover:border-accent transition-colors"><div className="flex justify-between gap-4"><div><div className="font-mono text-[10px] text-accent uppercase">{brand?.name || model.brand_id}</div><h3 className="font-display font-semibold text-[17px] mt-1">{model.name}</h3></div><div className="text-right"><div className="font-display font-bold text-xl">{hours != null ? `${hours}h` : '—'}</div><div className="font-mono text-[9px] text-accent mt-1">per charge</div></div></div><div className="mt-4 flex gap-3 flex-wrap text-[10px] font-mono text-dim"><span>Case {totalBattery(model) != null ? `${totalBattery(model)}h` : '—'}</span><span>{price(model.price)}</span><span>{model.anc ? 'ANC' : '—'}</span></div></Link>;
}

export async function generateMetadata({ params }) {
  const { locale } = params;
  const title = locale === 'fr' ? 'Meilleurs écouteurs avec la meilleure autonomie en 2026' : 'Best Earbuds for Battery Life in 2026';
  return { title: `${title} | EarbudsTimeline`, description: locale === 'fr' ? 'Comparez les écouteurs offrant la meilleure autonomie, par charge et avec leur boîtier, selon les données disponibles.' : 'Compare earbuds with the best battery life per charge and with their charging case using available catalog data.', ...canonicalFor(`/${locale}/guides/best-battery-life-earbuds`) };
}

export default async function Page({ params }) {
  const { locale } = params;
  const fr = locale === 'fr';
  const [models, brands] = await Promise.all([getAllEarbuds(), getBrands()]);
  const bm = new Map(brands.map(b => [b.id, b]));
  const rows = models.map(model => ({ model, hours: battery(model) })).filter(r => r.hours != null).sort((a, b) => b.hours - a.hours);
  const best = rows.slice(0, 10);
  const under100 = rows.filter(r => n(r.model.price) != null && n(r.model.price) <= 100).slice(0, 5);
  const withCase = rows.filter(r => totalBattery(r.model) != null).sort((a, b) => totalBattery(b.model) - totalBattery(a.model)).slice(0, 5);
  const anc = rows.filter(r => r.model.anc).slice(0, 5);
  const title = fr ? 'Meilleurs écouteurs avec la meilleure autonomie en 2026' : 'Best Earbuds for Battery Life in 2026';
  const intro = fr ? 'Comparez l’autonomie annoncée des écouteurs par charge et, lorsque la donnée est disponible, l’autonomie totale avec le boîtier. Les valeurs proviennent du catalogue et peuvent varier selon l’usage.' : 'Compare advertised earbud battery life per charge and, when available, total battery life with the charging case. Catalog values can vary with real-world use.';
  const jsonLd = { '@context': 'https://schema.org', '@type': 'Article', headline: title, description: intro, url: `https://earbudstimeline.com/${locale}/guides/best-battery-life-earbuds`, dateModified: '2026-08-25', inLanguage: locale };
  const guideHref = slug => `/${locale}/guides/${slug}`;
  const section = (h, items, s) => <section className="mt-12"><h2 className="font-display font-semibold text-[25px]">{h}</h2><p className="text-dim text-sm mt-1">{s}</p><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-5">{items.map(r => <Card key={r.model.id} row={r} brand={bm.get(r.model.brand_id)} locale={locale} />)}</div></section>;
  return <><JsonLd data={jsonLd}/><article className="max-w-6xl mx-auto"><div className="font-mono text-xs text-accent uppercase mb-3">Battery · 2026</div><h1 className="font-display font-bold text-[34px] sm:text-[48px] leading-tight mb-4">{title}</h1><p className="text-dim text-[15px] sm:text-[17px] leading-7 max-w-3xl">{intro}</p><div className="mt-4 text-[10px] font-mono text-dim">{fr ? 'Dernière mise à jour : 25 août 2026' : 'Last updated: August 25, 2026'}</div>
  <section className="mt-8 grid grid-cols-2 lg:grid-cols-4 gap-3">{[['overall','OVERALL',best],['under100','UNDER $100',under100],['case','CASE',withCase],['anc','ANC',anc]].map(([id,l,x]) => <a key={id} href={`#${id}`} className="bg-panel border border-line rounded-xl p-4 hover:border-accent"><div className="font-mono text-accent text-xs">{l}</div><div className="font-display font-semibold mt-1">{x.length} picks</div></a>)}</section>
  <section id="overall" className="mt-12"><h2 className="font-display font-semibold text-[25px] mb-5">🔋 {fr ? 'Meilleure autonomie' : 'Best Battery Life Earbuds Overall'}</h2><div className="overflow-x-auto border border-line rounded-2xl bg-panel"><table className="w-full text-left text-xs"><thead className="border-b border-line font-mono text-[10px] text-dim uppercase"><tr><th className="p-4">#</th><th className="p-4">Earbuds</th><th className="p-4">Price</th><th className="p-4">Per charge</th><th className="p-4">Case</th></tr></thead><tbody>{best.map((r,i) => <tr key={r.model.id} className="border-b border-line last:border-0"><td className="p-4 text-accent">{i+1}</td><td className="p-4"><Link href={`/${locale}/ecouteurs/${r.model.id}`} className="font-semibold hover:text-accent">{r.model.name}</Link><div className="text-dim text-[10px]">{bm.get(r.model.brand_id)?.name || r.model.brand_id}</div></td><td className="p-4 font-mono">{price(r.model.price)}</td><td className="p-4 font-bold">{r.hours}h</td><td className="p-4">{totalBattery(r.model) != null ? `${totalBattery(r.model)}h` : '—'}</td></tr>)}</tbody></table></div></section>
  <div id="under100">{section(fr ? '💵 Meilleurs écouteurs avec grande autonomie sous 100 $' : '💵 Best Battery Life Earbuds Under $100', under100, fr ? 'Modèles sous 100 $ classés par autonomie par charge.' : 'Under-$100 models ranked by per-charge battery life.')}</div>
  <div id="case">{section(fr ? '🔋 Meilleure autonomie totale avec le boîtier' : '🔋 Best Total Battery Life with Case', withCase, fr ? 'Classement selon l’autonomie totale indiquée pour les écouteurs et leur boîtier.' : 'Ranked by the available total battery figure for earbuds and case.')}</div>
  <div id="anc">{section(fr ? '🔇 Meilleure autonomie avec ANC' : '🔇 Best Battery Life with ANC', anc, fr ? 'Parmi les modèles ANC disposant d’une donnée d’autonomie.' : 'Among ANC models with available battery-life data.')}</div>
  <section className="mt-14"><h2 className="font-display font-semibold text-[25px] mb-5">{fr ? 'Autonomie annoncée vs autonomie réelle' : 'Advertised vs real-world battery life'}</h2><p className="text-dim text-sm leading-7 max-w-3xl">{fr ? 'L’autonomie annoncée est généralement mesurée dans des conditions précises. Le volume, l’ANC, les codecs, les appels et d’autres fonctions peuvent réduire l’autonomie réelle. Nous conservons donc les valeurs du catalogue sans les présenter comme une garantie d’utilisation.' : 'Advertised battery life is usually measured under specific conditions. Volume, ANC, codecs, calls and other features can reduce real-world battery life. We therefore present catalog figures without treating them as a guarantee of actual use.'}</p></section>
  <section className="mt-14"><h2 className="font-display font-semibold text-[25px] mb-5">{fr ? 'Méthodologie' : 'Methodology'}</h2><p className="text-dim text-sm leading-7 max-w-3xl">{fr ? 'Le classement utilise l’autonomie par charge disponible dans le catalogue. Une seconde section classe les modèles lorsque l’autonomie totale avec le boîtier est disponible. Aucune valeur manquante n’est inventée.' : 'The ranking uses per-charge battery life available in the catalog. A separate section ranks models when total battery life with the case is available. Missing values are not invented.'}</p></section>
  <section className="mt-14 grid md:grid-cols-2 gap-4"><div className="border border-line rounded-2xl p-6 bg-panel"><h2 className="font-display font-semibold text-xl">{fr ? 'Guides associés' : 'Related guides'}</h2><div className="mt-4 space-y-2 text-sm"><Link className="block hover:text-accent" href={guideHref('best-wireless-earbuds')}>→ Best Wireless Earbuds</Link><Link className="block hover:text-accent" href={guideHref('best-earbuds-under-100')}>→ Best Earbuds Under $100</Link><Link className="block hover:text-accent" href={guideHref('best-earbuds-for-sport')}>→ Best Sport Earbuds</Link></div></div><div className="border border-accent/30 rounded-2xl p-6 bg-panel"><h2 className="font-display font-semibold text-xl">{fr ? 'Explorer le catalogue' : 'Explore the catalog'}</h2><Link className="inline-block mt-4 text-accent font-mono text-xs uppercase" href={`/${locale}/ecouteurs`}>{fr ? 'Voir le catalogue →' : 'Browse catalog →'}</Link></div></section>
  <section className="mt-14"><h2 className="font-display font-semibold text-[25px] mb-5">FAQ</h2><div className="divide-y divide-line border-y border-line">{(fr ? [['Quels écouteurs ont la meilleure autonomie ?','Le classement ci-dessus met en avant les modèles ayant la plus grande autonomie par charge parmi les données disponibles dans notre catalogue.'],['Quelle est une bonne autonomie pour des écouteurs ?','Cela dépend de l’usage. Pour une journée avec plusieurs sessions, une bonne autonomie par charge peut réduire la fréquence de recharge, mais l’autonomie réelle varie selon les fonctions utilisées.'],['L’ANC réduit-il l’autonomie ?','L’ANC peut augmenter la consommation et donc réduire l’autonomie selon le modèle et les conditions d’utilisation.'],['L’autonomie du boîtier compte-t-elle ?','Oui. Elle indique combien de recharges supplémentaires le boîtier peut fournir et complète l’autonomie d’une seule charge.']] : [['Which earbuds have the best battery life?','The ranking above highlights models with the longest per-charge battery life among the data available in our catalog.'],['What is a good battery life for earbuds?','It depends on usage. For several sessions per day, longer per-charge battery life can reduce charging frequency, but real-world battery life varies with features and conditions.'],['Does ANC reduce battery life?','ANC can increase power consumption and therefore reduce battery life depending on the model and usage conditions.'],['Does case battery life matter?','Yes. It indicates how many additional recharges the case can provide and complements the single-charge battery figure.']]).map(([q,a]) => <details key={q} className="py-4"><summary className="cursor-pointer font-display font-medium">{q}</summary><p className="text-dim text-sm leading-7 mt-3 max-w-3xl">{a}</p></details>)}</div></section></article><Footer /></>;
}
