import { Link } from '@/i18n/navigation';
import { getAllEarbuds, getBrands, getAncIntelligence } from '@/lib/queries';
import { canonicalFor, JsonLd } from '@/lib/seo';
import { Footer } from '@/components/UI';

export const revalidate = 3600;

export async function generateMetadata({ params }) {
  const { locale } = params;
  const title = locale === 'fr' ? 'Les meilleurs écouteurs sans fil pas chers : sélection par prix et rapport qualité-prix' : 'Best Budget Earbuds: Best Picks by Price, Value and Features';
  const description = locale === 'fr' ? 'Comparez les meilleurs écouteurs abordables par budget, autonomie, ANC, résistance à l’eau et rapport qualité-prix.' : 'Compare the best budget earbuds by price, battery life, ANC, water resistance and overall value.';
  return { title: `${title} | EarbudsTimeline`, description, ...canonicalFor(`/${locale}/guides/best-budget-earbuds`) };
}

const n = (v) => Number.isFinite(Number(v)) ? Number(v) : null;
const clamp = (v, min = 0, max = 100) => Math.max(min, Math.min(max, v));
const batteryScore = (h) => h == null ? null : clamp((h / 12) * 100);
const priceScore = (p) => p == null ? null : clamp(100 - ((p - 20) / 80) * 100);
const weightScore = (w) => w == null ? null : clamp(100 - ((w - 4) / 6) * 100);
const waterScore = (v) => { const m = String(v || '').toUpperCase().match(/IPX?(\d)/); return m ? clamp((Number(m[1]) / 8) * 100) : null; };
const valueIndex = (m, anc) => {
  const p = n(m.price); if (p == null || p > 100) return null;
  const parts = [];
  const add = (v, w) => { if (v != null) parts.push([v, w]); };
  add(priceScore(p), 30); add(batteryScore(n(m.battery_bud_h)), 20); add(weightScore(n(m.weight_g)), 10); add(waterScore(m.water_rating), 10);
  add(anc?.anc_score != null ? n(anc.anc_score) : (m.anc === true ? 55 : null), 20); add(m.bluetooth ? 70 : null, 10);
  const total = parts.reduce((s, [, w]) => s + w, 0); return total ? Math.round(parts.reduce((s, [v, w]) => s + v * w, 0) / total) : null;
};
const formatPrice = (v) => n(v) == null ? '—' : `$${Math.round(n(v))}`;

function Score({ value, label }) { return <div className="flex items-center gap-2"><span className="font-mono text-[10px] text-dim w-16">{label}</span><div className="h-1.5 flex-1 rounded-full bg-line overflow-hidden"><div className="h-full bg-accent rounded-full" style={{ width: `${value ?? 0}%` }} /></div><span className="font-mono text-[10px] w-7 text-right">{value ?? '—'}</span></div>; }
function Card({ row, brand, badge }) { const { model, intelligence, value } = row; return <Link href={`/ecouteurs/${model.id}`} className="block bg-panel border border-line rounded-2xl p-5 hover:border-accent transition-colors"><div className="flex justify-between gap-4"><div className="min-w-0"><div className="font-mono text-[10px] text-accent uppercase tracking-[.12em]">{brand?.name || model.brand_id}</div><h3 className="font-display font-semibold text-[17px] mt-1">{model.name}</h3></div><div className="text-right shrink-0"><div className="font-display font-bold text-xl">{formatPrice(model.price)}</div>{badge && <div className="font-mono text-[9px] text-accent mt-1">{badge}</div>}</div></div><div className="mt-4 space-y-2"><Score label="Value" value={value} /><Score label="Battery" value={batteryScore(n(model.battery_bud_h))} />{intelligence?.anc_score != null && <Score label="ANC" value={Math.round(n(intelligence.anc_score))} />}</div><div className="mt-4 pt-3 border-t border-line flex gap-3 flex-wrap text-[10px] font-mono text-dim"><span>{n(model.battery_bud_h) ?? '—'}h battery</span><span>{model.water_rating || '—'}</span><span>{n(model.weight_g) ? `${n(model.weight_g)}g` : '—'}</span></div></Link>; }

export default async function BestBudgetEarbudsPage({ params }) {
  const { locale } = params; const fr = locale === 'fr';
  const [models, brands, ancRows] = await Promise.all([getAllEarbuds(), getBrands(), getAncIntelligence()]);
  const brandMap = new Map(brands.map((b) => [b.id, b])); const ancMap = new Map(ancRows.map((r) => [r.earbud_id, r]));
  const rows = models.filter((m) => n(m.price) != null && n(m.price) <= 100).map((model) => ({ model, intelligence: ancMap.get(model.id), value: valueIndex(model, ancMap.get(model.id)) }));
  const ranked = [...rows].sort((a, b) => (b.value ?? -1) - (a.value ?? -1));
  const under = (limit) => ranked.filter((r) => n(r.model.price) <= limit).slice(0, 5);
  const best = ranked.slice(0, 8);
  const bestAnc = [...rows].filter((r) => r.intelligence?.anc_score != null).sort((a, b) => n(b.intelligence.anc_score) - n(a.intelligence.anc_score)).slice(0, 5);
  const bestBattery = [...rows].filter((r) => n(r.model.battery_bud_h) != null).sort((a, b) => n(b.model.battery_bud_h) - n(a.model.battery_bud_h)).slice(0, 5);
  const bestSport = [...rows].filter((r) => waterScore(r.model.water_rating) != null).sort((a, b) => (waterScore(b.model.water_rating) || 0) + (weightScore(n(b.model.weight_g)) || 0) - ((waterScore(a.model.water_rating) || 0) + (weightScore(n(a.model.weight_g)) || 0))).slice(0, 5);
  const title = fr ? 'Les meilleurs écouteurs sans fil pas chers' : 'Best Budget Earbuds';
  const intro = fr ? 'Les meilleurs écouteurs budget ne sont pas simplement les moins chers. Nous comparons les modèles jusqu’à 100 $ selon le prix, l’autonomie, le poids, la résistance à l’eau, les fonctions sans fil et, lorsqu’il existe, notre intelligence ANC.' : 'The best budget earbuds are not simply the cheapest. We compare models up to $100 using price, battery life, weight, water resistance, wireless features and, where available, our ANC Intelligence.';
  const sections = fr ? [['Notre Budget Value Index', 'Le score privilégie le prix mais récompense aussi l’autonomie, le poids, la résistance à l’eau, les fonctions sans fil et les performances ANC documentées. Il s’agit d’un indice de valeur transparent, pas d’un test audio de laboratoire.'], ['Pourquoi le prix seul est trompeur', 'Un modèle à 30 $ peut être moins intéressant qu’un modèle à 45 $ si ce dernier apporte une meilleure autonomie, un ANC documenté et davantage de fonctions utiles. Le classement cherche donc le meilleur compromis plutôt que le prix minimum.'], ['Choisir selon son budget', 'Nous séparons les meilleurs modèles sous 30 $, 50 $, 75 $ et 100 $. Cela évite qu’un modèle à 95 $ écrase automatiquement toutes les options vraiment économiques.'], ['Une recommandation doit montrer ses compromis', 'Chaque carte affiche le prix, l’autonomie, le poids, la résistance à l’eau et les données ANC disponibles. Les informations absentes restent absentes plutôt que d’être inventées.']] : [['Our Budget Value Index', 'The score rewards low price while also considering battery life, weight, water resistance, wireless features and documented ANC performance. It is a transparent value index, not a laboratory audio score.'], ['Why price alone is misleading', 'A $30 model can be worse value than a $45 model if the latter delivers better battery life, documented ANC and more useful features. We therefore rank the compromise, not simply the lowest price.'], ['Choose by budget', 'We separate the strongest options under $30, $50, $75 and $100 so a $95 model does not automatically dominate genuinely cheap alternatives.'], ['Recommendations should expose trade-offs', 'Each card shows price, battery, weight, water resistance and available ANC data. Missing information stays missing instead of being invented.']];
  const jsonLd = { '@context': 'https://schema.org', '@type': 'Article', headline: title, description: intro, url: `https://earbudstimeline.com/${locale}/guides/best-budget-earbuds` };
  const section = (heading, items, badge) => <section className="mt-12"><div className="mb-5"><h2 className="font-display font-semibold text-[25px]">{heading}</h2><p className="text-dim text-sm mt-1">{badge}</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{items.map((r) => <Card key={r.model.id} row={r} brand={brandMap.get(r.model.brand_id)} badge={badge} />)}</div></section>;
  return <><JsonLd data={jsonLd} /><article className="max-w-6xl mx-auto"><div className="font-mono text-xs text-accent uppercase tracking-[.14em] mb-3">Budget Intelligence</div><h1 className="font-display font-bold text-[34px] sm:text-[48px] leading-tight mb-4">{title}</h1><p className="text-dim text-[15px] sm:text-[17px] leading-7 max-w-3xl">{intro}</p>
    <div className="mt-8 grid grid-cols-2 lg:grid-cols-4 gap-3">{[30, 50, 75, 100].map((limit) => <a key={limit} href={`#under-${limit}`} className="bg-panel border border-line rounded-xl p-4 hover:border-accent"><div className="font-mono text-accent text-xs">UNDER ${limit}</div><div className="font-display font-semibold mt-1">{under(limit).length} picks</div></a>)}</div>
    {section(fr ? '🏆 Meilleur rapport qualité-prix' : '🏆 Best Budget Value', best, 'Budget Value Index /100')}
    {[30,50,75,100].map((limit) => <div id={`under-${limit}`} key={limit}>{section(fr ? `Meilleurs sous ${limit} $` : `Best Under $${limit}`, under(limit), fr ? 'Sélection par budget' : 'Budget shortlist')}</div>)}
    {section(fr ? '🔇 Meilleur ANC budget' : '🔇 Best Budget ANC', bestAnc, 'ANC Intelligence /100')}
    {section(fr ? '🔋 Meilleure autonomie budget' : '🔋 Best Budget Battery', bestBattery, fr ? 'Autonomie annoncée par écouteur' : 'Rated per-earbud battery life')}
    {section(fr ? '🏃 Meilleurs pour le sport' : '🏃 Best Budget Sport', bestSport, fr ? 'Résistance à l’eau + poids' : 'Water resistance + weight')}
    <section className="mt-14"><h2 className="font-display font-semibold text-[25px] mb-5">{fr ? 'Comment nous calculons la valeur' : 'How we calculate value'}</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{(fr ? [['Prix','30%'],['Autonomie','20%'],['ANC documenté','20%'],['Poids','10%'],['Résistance à l’eau','10%'],['Fonctions sans fil','10%']] : [['Price','30%'],['Battery','20%'],['Documented ANC','20%'],['Weight','10%'],['Water resistance','10%'],['Wireless features','10%']]).map(([label, weight]) => <div key={label} className="border border-line rounded-xl p-4 bg-panel"><div className="font-mono text-accent text-xs">{weight}</div><div className="font-display font-semibold mt-1">{label}</div></div>)}</div><p className="text-dim text-xs leading-6 mt-4 max-w-3xl">{fr ? 'Les dimensions sans données ne sont pas remplacées par une note parfaite ou nulle : le score est recalculé sur les critères disponibles. L’ANC utilise notre moteur lorsque le score existe.' : 'Dimensions without data are not silently replaced with a perfect or zero score: the index is recalculated across available criteria. ANC uses our intelligence engine when a score exists.'}</p></section>
    <section className="mt-14 grid md:grid-cols-2 gap-4"><div className="border border-line rounded-2xl p-6 bg-panel"><h2 className="font-display font-semibold text-xl">{fr ? 'Pourquoi notre approche est différente' : 'Why our approach is different'}</h2><p className="text-dim text-sm leading-7 mt-3">{fr ? 'Les guides spécialisés peuvent exceller sur le son, les appels ou l’isolation grâce à des tests directs. Notre indice ne prétend pas les remplacer : il apporte une comparaison reproductible des données disponibles et montre clairement les compromis.' : 'Specialist guides can excel at sound, calls or isolation through direct testing. Our index does not replace them: it provides a reproducible comparison of available data and exposes the trade-offs.'}</p></div><div className="border border-accent/30 rounded-2xl p-6 bg-panel"><h2 className="font-display font-semibold text-xl">{fr ? 'Besoin d’une recommandation personnalisée ?' : 'Need a personalized recommendation?'}</h2><p className="text-dim text-sm leading-7 mt-3">{fr ? 'Le prix n’est qu’un point de départ. Utilisez le Finder pour trouver le modèle adapté à vos usages.' : 'Price is only a starting point. Use the Finder to find the model that matches your needs.'}</p><Link href="/trouver-mes-ecouteurs" className="inline-block mt-4 text-accent font-mono text-xs uppercase">{fr ? 'Ouvrir le Finder →' : 'Open Finder →'}</Link></div></section>
    <section className="mt-14"><h2 className="font-display font-semibold text-[25px] mb-5">FAQ</h2><div className="divide-y divide-line border-y border-line">{(fr ? [['Quel est le meilleur écouteur pas cher ?','Le meilleur choix dépend du budget et des priorités. Notre Budget Value Index cherche le meilleur compromis plutôt que le prix le plus bas.'],['Quel budget faut-il prévoir ?','50 $ est un bon point de comparaison, mais des modèles intéressants existent sous 30 $ et certains sous 75 ou 100 $ apportent davantage de fonctions.'],['Le score mesure-t-il la qualité sonore ?','Non. Il s’agit d’un indice de valeur basé sur les données disponibles. La qualité sonore doit être vérifiée dans les tests dédiés lorsqu’ils existent.'],['Pourquoi certains modèles n’ont-ils pas de score ANC ?','Notre moteur ANC ne calcule un score que lorsque les preuves sont suffisantes. Une absence de score ne signifie pas que l’ANC est mauvais.']] : [['What are the best cheap earbuds?','The best choice depends on your budget and priorities. Our Budget Value Index looks for the strongest compromise rather than the lowest price.'],['How much should I spend?','$50 is a useful benchmark, but strong options exist below $30, while models under $75 or $100 can add more features.'],['Does the score measure sound quality?','No. It is a value index based on available data. Sound quality should be checked in dedicated testing when available.'],['Why do some models have no ANC score?','Our ANC engine only calculates a score when the evidence is sufficient. Missing data does not mean the ANC is poor.']]).map(([q,a]) => <details key={q} className="py-4"><summary className="cursor-pointer font-display font-medium">{q}</summary><p className="text-dim text-sm leading-7 mt-3 max-w-3xl">{a}</p></details>)}</div></section>
  </article><Footer /></>;
}
