export const GUIDE_PAGES = [
  {
    slug: 'best-budget-earbuds',
    priority: 0.9,
    en: {
      title: 'Best Budget Earbuds',
      description: 'A practical guide to the best budget wireless earbuds, with clear criteria for price, features, battery life and everyday value.',
      intro: 'The best budget earbuds are not simply the cheapest models. They are the models that deliver the strongest mix of sound, battery life, comfort and useful features for the money.',
      sections: [
        ['What makes a good budget pair?', 'Look beyond the launch price. Battery life, water resistance, Bluetooth support, ANC and weight can make a cheaper pair much better or worse for daily use.'],
        ['How we compare them', 'We start with price, then look at the specifications available in our database. We separate objective specifications from subjective claims so the shortlist stays transparent.'],
        ['Who should buy budget earbuds?', 'Budget earbuds are ideal for a first pair, a backup pair, commuting, exercise or anyone who does not need every premium feature.'],
      ],
    },
    fr: {
      title: 'Les meilleurs écouteurs sans fil pas chers',
      description: 'Guide des meilleurs écouteurs sans fil abordables : prix, autonomie, fonctions, confort et rapport qualité-prix.',
      intro: 'Les meilleurs écouteurs abordables ne sont pas forcément les moins chers. Il faut rechercher le meilleur équilibre entre son, autonomie, confort et fonctionnalités.',
      sections: [
        ['Qu’est-ce qu’un bon modèle abordable ?', 'Le prix ne suffit pas. L’autonomie, la résistance à l’eau, le Bluetooth, l’ANC et le poids peuvent faire une grande différence au quotidien.'],
        ['Comment les comparer', 'Nous partons du prix puis comparons les caractéristiques disponibles dans notre base. Les données objectives sont séparées des appréciations éditoriales.'],
        ['Pour qui ?', 'Ils conviennent à un premier achat, à une paire de secours, aux transports ou au sport sans payer pour toutes les fonctions premium.'],
      ],
    },
    filter: (m) => Number.isFinite(Number(m.price)) && Number(m.price) <= 100,
    sort: (a, b) => Number(a.price) - Number(b.price),
  },
  {
    slug: 'best-wireless-earbuds-under-100',
    priority: 0.9,
    en: { title: 'Best Wireless Earbuds Under $100', description: 'Find the best wireless earbuds under $100 by comparing price, ANC, battery life, Bluetooth and everyday specifications.', intro: 'A $100 ceiling still leaves a wide range of wireless earbuds. The right choice depends on which features matter most to you.', sections: [['What to prioritize under $100', 'Prioritize the features you will use every day: battery life, fit, water resistance, ANC when available and reliable Bluetooth connectivity.'], ['Price is only the first filter', 'Two earbuds can cost almost the same while offering very different battery, weight or ANC specifications. Compare the full specification set before choosing.'], ['A good $100 shortlist', 'Use the live catalogue below as a starting point, then open each product page for the complete specifications and timeline context.']] },
    fr: { title: 'Les meilleurs écouteurs sans fil à moins de 100 $', description: 'Comparez les meilleurs écouteurs sans fil à moins de 100 $ selon le prix, l’ANC, l’autonomie et le Bluetooth.', intro: 'Avec un plafond de 100 $, le choix reste très large. Le meilleur modèle dépend surtout des fonctions que vous utilisez réellement.', sections: [['Les critères prioritaires', 'Autonomie, confort, résistance à l’eau, ANC lorsqu’il est disponible et connectivité Bluetooth sont de bons points de départ.'], ['Le prix ne suffit pas', 'Deux modèles au même prix peuvent avoir une autonomie, un poids ou un ANC très différents.'], ['Une première sélection', 'Utilisez la sélection ci-dessous puis ouvrez chaque fiche pour consulter toutes les caractéristiques.']] },
    filter: (m) => Number.isFinite(Number(m.price)) && Number(m.price) <= 100,
    sort: (a, b) => Number(a.price) - Number(b.price),
  },
  {
    slug: 'best-wireless-earbuds-for-calls',
    priority: 0.9,
    en: { title: 'Best Wireless Earbuds for Calls', description: 'Guide to choosing wireless earbuds for calls, meetings and voice conversations, with a transparent specification-based approach.', intro: 'For calls, microphone performance matters as much as sound. Unfortunately, a product specification alone cannot fully describe real-world voice quality, so our guide focuses on what can be verified.', sections: [['What matters for calls', 'Look for a good microphone system, wind-noise handling, stable Bluetooth and a comfortable fit for long meetings. Where microphone testing is unavailable, we avoid pretending a specification proves call quality.'], ['For work and meetings', 'Battery life and comfort become particularly important when earbuds are used for several calls in a row.'], ['How to use this guide', 'Treat the catalogue as a shortlist and check the individual product page for the specifications currently available.']] },
    fr: { title: 'Les meilleurs écouteurs sans fil pour les appels', description: 'Guide pour choisir des écouteurs sans fil adaptés aux appels, réunions et conversations vocales.', intro: 'Pour les appels, la qualité du microphone compte autant que le son. Une fiche technique ne suffit cependant pas à prédire la qualité réelle de la voix.', sections: [['Les critères importants', 'Microphones, réduction du vent, stabilité Bluetooth et confort sont essentiels. Lorsque nous ne disposons pas de tests micro, nous ne prétendons pas qu’une simple fiche technique prouve la qualité des appels.'], ['Pour le travail', 'L’autonomie et le confort deviennent particulièrement importants pendant les longues réunions.'], ['Comment utiliser cette page', 'Considérez la sélection comme un point de départ puis consultez chaque fiche produit.']] },
    sort: (a, b) => Number(b.battery_bud_h) - Number(a.battery_bud_h),
  },
  {
    slug: 'best-noise-cancelling-earbuds', priority: 0.95,
    en: { title: 'Best Noise Cancelling Earbuds', description: 'Compare wireless earbuds with active noise cancellation and learn which specifications matter when choosing ANC earbuds.', intro: 'Active noise cancellation is one of the most useful features for commuting, travel and focused listening. But ANC quality cannot be reduced to a simple yes/no checkbox.', sections: [['ANC is more than a checkbox', 'The database records whether ANC is offered, while real-world cancellation also depends on fit, microphones, processing and the environment.'], ['For commuting and travel', 'Combine ANC with a secure fit, good battery life and the right water resistance for your routine.'], ['Compare the specifications', 'Start with the ANC-enabled catalogue below, then open individual products to inspect battery, weight, Bluetooth and other details.']] },
    fr: { title: 'Les meilleurs écouteurs avec réduction de bruit', description: 'Comparez les écouteurs sans fil avec réduction active du bruit et les caractéristiques importantes pour l’ANC.', intro: 'La réduction active du bruit est particulièrement utile dans les transports, en voyage et pour travailler. Mais l’ANC ne se résume pas à une case oui/non.', sections: [['L’ANC ne fait pas tout', 'Notre base indique si l’ANC est disponible. La qualité réelle dépend aussi de l’ajustement, des microphones et du traitement du signal.'], ['Transport et voyage', 'Associez l’ANC à un bon maintien, une autonomie suffisante et une résistance à l’eau adaptée à votre usage.'], ['Comparer les caractéristiques', 'Commencez par les modèles ANC puis consultez chaque fiche pour l’autonomie, le poids et le Bluetooth.']] },
    filter: (m) => m.anc === true,
    sort: (a, b) => Number(b.battery_bud_h) - Number(a.battery_bud_h),
  },
  {
    slug: 'best-earbuds-for-small-ears', priority: 0.85,
    en: { title: 'Best Earbuds for Small Ears', description: 'A practical guide to choosing earbuds for small ears, focusing on weight, fit and the specifications that can be checked before buying.', intro: 'Small ears can make fit more important than headline specifications. Weight is measurable, but physical comfort still depends on ear shape and the supplied tips.', sections: [['What to look for', 'Lower weight can help, but it is not a guarantee of a good fit. Tip selection, nozzle shape and the physical design matter too.'], ['Avoid choosing on weight alone', 'A lightweight earbud can still be uncomfortable if its shape does not match your ear.'], ['Our shortlist', 'The catalogue is ordered by weight as a useful first filter, not as a definitive comfort ranking.']] },
    fr: { title: 'Les meilleurs écouteurs pour petites oreilles', description: 'Guide pour choisir des écouteurs adaptés aux petites oreilles, avec un focus sur le poids et le confort.', intro: 'Pour les petites oreilles, le maintien peut être plus important que les caractéristiques marketing. Le poids est mesurable, mais le confort dépend aussi de la morphologie.', sections: [['Que regarder', 'Un poids réduit peut aider, mais ne garantit pas un bon ajustement. Les embouts et la forme comptent aussi.'], ['Ne pas choisir uniquement sur le poids', 'Un écouteur léger peut rester inconfortable si sa forme ne convient pas.'], ['Notre sélection', 'Le catalogue est trié par poids comme premier filtre, pas comme classement absolu du confort.']] },
    sort: (a, b) => Number(a.weight_g) - Number(b.weight_g),
  },
  {
    slug: 'best-gaming-earbuds', priority: 0.85,
    en: { title: 'Best Gaming Earbuds', description: 'Guide to gaming earbuds, covering Bluetooth, weight, battery life and the limitations of specification-only comparisons.', intro: 'Gaming earbuds need low perceived latency, a stable connection, comfort and enough battery for long sessions. A Bluetooth version alone does not prove gaming latency.', sections: [['What gamers should check', 'Look for low-latency modes when documented, stable wireless connectivity, comfort and battery life.'], ['PC and console gaming', 'Compatibility varies by platform and connection method. Always check the product documentation before buying for a specific console or PC setup.'], ['Use the database intelligently', 'The shortlist below is organized around measurable specifications; it is not presented as a substitute for latency testing.']] },
    fr: { title: 'Les meilleurs écouteurs pour le gaming', description: 'Guide des écouteurs gaming : Bluetooth, poids, autonomie et limites des comparaisons basées uniquement sur les fiches techniques.', intro: 'Pour jouer, il faut surtout une latence faible, une connexion stable, du confort et une autonomie suffisante.', sections: [['Ce que les joueurs doivent vérifier', 'Modes faible latence lorsqu’ils sont documentés, stabilité, confort et autonomie.'], ['PC et consoles', 'La compatibilité dépend de la plateforme et du mode de connexion. Vérifiez toujours la documentation.'], ['Utiliser la base intelligemment', 'La sélection repose sur des caractéristiques mesurables et ne remplace pas des tests de latence.']] },
    sort: (a, b) => Number(b.battery_bud_h) - Number(a.battery_bud_h),
  },
  {
    slug: 'best-earbuds-for-gaming-pc', priority: 0.8,
    en: { title: 'Best Earbuds for Gaming on PC', description: 'Find earbuds worth considering for PC gaming and learn which wireless specifications matter before you buy.', intro: 'PC gaming introduces extra compatibility questions. Bluetooth support, latency, microphone behavior and connection stability all matter.', sections: [['PC gaming checklist', 'Check the connection method, latency mode, microphone support and whether the PC needs a separate Bluetooth adapter.'], ['Wireless does not automatically mean low latency', 'Bluetooth version is useful context, but it is not a direct latency measurement.'], ['Start with the catalogue', 'Use the products below as candidates and verify PC-specific compatibility on the individual product documentation.']] },
    fr: { title: 'Les meilleurs écouteurs pour jouer sur PC', description: 'Guide pour choisir des écouteurs sans fil adaptés au gaming sur PC.', intro: 'Sur PC, la compatibilité ajoute plusieurs contraintes : connexion, latence, microphone et stabilité.', sections: [['Checklist PC', 'Vérifiez le mode de connexion, la latence, le microphone et la nécessité éventuelle d’un adaptateur Bluetooth.'], ['Bluetooth ne signifie pas automatiquement faible latence', 'La version Bluetooth donne du contexte mais ne mesure pas directement la latence.'], ['Commencer par le catalogue', 'Utilisez les modèles comme candidats puis vérifiez leur compatibilité PC.']] },
    sort: (a, b) => Number(b.bluetooth || '').toString().localeCompare(Number(a.bluetooth || '').toString()),
  },
  {
    slug: 'best-gaming-earbuds-under-100', priority: 0.8,
    en: { title: 'Best Gaming Earbuds Under $100', description: 'A guide to affordable gaming earbuds under $100, with a focus on latency, battery life, comfort and compatibility.', intro: 'Under $100, the goal is to find the best compromise between gaming features and everyday usability.', sections: [['The $100 trade-off', 'Affordable models may prioritize battery life or general audio features instead of advanced gaming modes.'], ['What matters most', 'For gaming, check latency behavior, connection stability, microphone support and comfort before focusing on small specification differences.'], ['Browse the candidates', 'The shortlist below starts with models under $100 and lets you inspect their full specifications.']] },
    fr: { title: 'Les meilleurs écouteurs gaming à moins de 100 $', description: 'Guide des écouteurs gaming abordables à moins de 100 $, avec un focus sur latence, autonomie et compatibilité.', intro: 'Sous les 100 $, il faut trouver le meilleur compromis entre fonctions gaming et usage quotidien.', sections: [['Le compromis des 100 $', 'Les modèles abordables privilégient parfois l’autonomie ou les fonctions générales plutôt que les modes gaming avancés.'], ['Les vrais critères', 'Vérifiez latence, stabilité, microphone et confort avant les petites différences de fiche technique.'], ['Voir les candidats', 'La sélection commence par les modèles sous 100 $ et renvoie vers leurs fiches complètes.']] },
    filter: (m) => Number.isFinite(Number(m.price)) && Number(m.price) <= 100,
    sort: (a, b) => Number(a.price) - Number(b.price),
  },
  {
    slug: 'best-sport-earbuds', priority: 0.85,
    en: { title: 'Best Sport Earbuds', description: 'Guide to sport earbuds, focusing on water resistance, weight, battery life and secure everyday use.', intro: 'Sport earbuds need to stay comfortable and secure while handling sweat and movement. Water resistance is one of the easiest objective filters.', sections: [['Water resistance matters', 'Check the stated water-resistance rating rather than assuming that every wireless earbud is suitable for exercise.'], ['Weight and battery', 'Lower weight can help during long sessions, while sufficient battery life reduces charging interruptions.'], ['Fit still comes first', 'No specification can guarantee that an earbud will stay secure in your ears.']] },
    fr: { title: 'Les meilleurs écouteurs pour le sport', description: 'Guide des écouteurs sport avec focus sur résistance à l’eau, poids, autonomie et maintien.', intro: 'Pour le sport, les écouteurs doivent rester confortables et bien tenir tout en résistant à la transpiration.', sections: [['La résistance à l’eau', 'Vérifiez l’indice annoncé plutôt que de supposer qu’un écouteur sans fil convient au sport.'], ['Poids et autonomie', 'Un poids réduit peut améliorer le confort et une bonne autonomie limite les recharges.'], ['Le maintien reste essentiel', 'Aucune fiche technique ne garantit que le modèle restera parfaitement en place dans vos oreilles.']] },
    sort: (a, b) => String(b.water_rating || '').localeCompare(String(a.water_rating || '')) || Number(a.weight_g) - Number(b.weight_g),
  },
  {
    slug: 'earbuds-with-longest-battery-life', priority: 0.8,
    en: { title: 'Earbuds With the Longest Battery Life', description: 'Compare earbuds by rated per-earbud battery life and understand the difference between earbud and case endurance.', intro: 'Battery claims can be confusing because manufacturers often quote the combined endurance with the charging case. This page focuses on the rated earbud battery figure stored in our database.', sections: [['Earbud battery vs case battery', 'The earbud figure tells you how long the buds can operate before returning to the case. Case endurance describes the total additional charging capacity.'], ['Why battery life matters', 'Longer rated battery life is useful for travel, workdays and long listening sessions.'], ['Compare the numbers', 'Use the table below as an objective starting point, then consider weight, fit and other specifications.']] },
    fr: { title: 'Les écouteurs avec la meilleure autonomie', description: 'Comparez les écouteurs selon leur autonomie annoncée et distinguez autonomie des écouteurs et capacité du boîtier.', intro: 'Les chiffres d’autonomie sont parfois difficiles à comparer car les marques additionnent souvent les recharges du boîtier. Cette page se concentre sur l’autonomie annoncée des écouteurs.', sections: [['Écouteurs ou boîtier ?', 'L’autonomie des écouteurs indique le temps d’écoute avant de devoir les remettre dans le boîtier.'], ['Pourquoi l’autonomie compte', 'Une grande autonomie est pratique en voyage, au travail et pour les longues sessions.'], ['Comparer les chiffres', 'Utilisez les données comme point de départ puis prenez en compte le poids, le confort et les autres caractéristiques.']] },
    sort: (a, b) => Number(b.battery_bud_h) - Number(a.battery_bud_h),
  },
  {
    slug: 'airpods-vs-galaxy-buds', priority: 0.9,
    en: { title: 'AirPods vs Galaxy Buds', description: 'AirPods vs Galaxy Buds: compare Apple and Samsung wireless earbuds across generations, battery, ANC, weight and Bluetooth.', intro: 'AirPods and Galaxy Buds represent two of the most recognizable wireless-earbud families. The better choice depends heavily on ecosystem, device compatibility and the generation you compare.', sections: [['Apple vs Samsung ecosystems', 'AirPods are most deeply integrated with Apple devices, while Galaxy Buds are designed around Samsung and Android experiences. Cross-platform use is possible, but some features may differ.'], ['Compare the generation, not just the brand', 'An older AirPods model should not automatically be compared with a newer Galaxy Buds generation. Compare release date, price and specifications side by side.'], ['Use the live comparison', 'The candidates below are grouped from the current database so you can open individual product pages and compare exact specifications.']] },
    fr: { title: 'AirPods vs Galaxy Buds', description: 'AirPods vs Galaxy Buds : comparez les écouteurs Apple et Samsung selon générations, autonomie, ANC, poids et Bluetooth.', intro: 'AirPods et Galaxy Buds sont deux grandes familles d’écouteurs sans fil. Le meilleur choix dépend surtout de l’écosystème et de la génération comparée.', sections: [['Écosystèmes Apple et Samsung', 'Les AirPods sont particulièrement intégrés aux appareils Apple, tandis que les Galaxy Buds sont pensés autour de Samsung et Android.'], ['Comparer les générations', 'Un ancien AirPods ne doit pas être opposé automatiquement à une génération récente de Galaxy Buds.'], ['Utiliser la comparaison', 'La sélection ci-dessous provient de la base actuelle et permet d’ouvrir les fiches détaillées.']] },
    compare: true,
  },
  {
    slug: 'nothing-ear-reviews', priority: 0.75,
    en: { title: 'Nothing Ear Reviews', description: 'Explore Nothing Ear earbuds by generation, specifications, battery life, ANC, Bluetooth and launch price.', intro: 'Nothing has built a recognizable earbud family around transparent design and a distinctive software experience. Explore the models in chronological context instead of treating every generation as an isolated product.', sections: [['What to compare', 'Look at launch price, ANC, battery life, weight, water resistance and Bluetooth to understand how the family has evolved.'], ['Generations matter', 'A newer Nothing Ear is not automatically better for every buyer. Compare the exact generation and the features you actually need.'], ['Explore every model', 'The live catalogue below links directly to the individual Nothing product pages.']] },
    fr: { title: 'Tests et avis des Nothing Ear', description: 'Découvrez les écouteurs Nothing Ear par génération : caractéristiques, autonomie, ANC, Bluetooth et prix.', intro: 'Nothing a construit une famille d’écouteurs reconnaissable grâce à son design transparent et son expérience logicielle. Explorez les modèles dans leur contexte chronologique.', sections: [['Que comparer', 'Prix de lancement, ANC, autonomie, poids, résistance à l’eau et Bluetooth permettent de suivre l’évolution de la gamme.'], ['Les générations comptent', 'Le modèle le plus récent n’est pas automatiquement le meilleur pour chaque utilisateur.'], ['Explorer chaque modèle', 'Le catalogue ci-dessous renvoie directement vers les fiches Nothing disponibles.']] },
    brand: 'nothing',
    sort: (a, b) => new Date(b.release_date) - new Date(a.release_date),
  },
];

export function getGuide(slug) {
  return GUIDE_PAGES.find((page) => page.slug === slug) || null;
}
