import { slugify } from './slug.js';

/** Parse a simple YAML frontmatter block. */
export function parseFrontmatter(rawContent) {
  const trimmed = rawContent.trim();
  if (!trimmed.startsWith('---')) return { data: {}, body: rawContent };

  const match = trimmed.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) return { data: {}, body: rawContent };

  const data = {};
  for (const line of match[1].split(/\r?\n/)) {
    const colonIndex = line.indexOf(':');
    if (colonIndex === -1) continue;
    const key = line.slice(0, colonIndex).trim();
    let value = line.slice(colonIndex + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    } else if (value.toLowerCase() === 'true') value = true;
    else if (value.toLowerCase() === 'false') value = false;
    else if (value !== '' && !Number.isNaN(Number(value))) value = Number(value);
    if (key) data[key] = value;
  }
  return { data, body: match[2] };
}

function escapeHtml(str) {
  return (str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Extract the editorial heading hierarchy from Markdown.
 * H1 is treated as the article title and excluded from the public TOC.
 * H2-H4 become navigable sections.
 */
export function extractTableOfContents(markdown) {
  if (!markdown) return [];

  const headings = [];
  const slugCounts = new Map();
  let inFence = false;

  for (const line of markdown.split(/\r?\n/)) {
    if (/^\s*```/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;

    const match = line.match(/^\s{0,3}(#{1,4})\s+(.+?)\s*#*\s*$/);
    if (!match) continue;

    const level = match[1].length;
    const title = match[2].trim().replace(/\[([^\]]+)\]\([^)]*\)/g, '$1').replace(/[*_`~]/g, '');
    if (!title) continue;

    // The H1 is the article title, not a TOC item.
    if (level === 1) continue;

    const baseId = slugify(title) || `section-${headings.length + 1}`;
    const count = slugCounts.get(baseId) || 0;
    slugCounts.set(baseId, count + 1);
    const id = count ? `${baseId}-${count + 1}` : baseId;

    headings.push({ id, title, level });
  }

  return headings;
}

/** Add stable IDs to H2-H4 generated by the Markdown parser. */
function addHeadingIds(html, tableOfContents) {
  if (!html || !tableOfContents?.length) return html;
  let index = 0;
  return html.replace(/<h([2-4])>([\s\S]*?)<\/h\1>/gi, (match, level, inner) => {
    const item = tableOfContents[index++];
    return item ? `<h${level} id="${escapeHtml(item.id)}">${inner}</h${level}>` : match;
  });
}

/** Convert simple Markdown to clean HTML compatible with the existing editor. */
export function markdownToHtml(markdown, tableOfContents = []) {
  if (!markdown) return '';
  let text = markdown.trim();
  const codeBlocks = [];
  const inlineCodes = [];

  text = text.replace(/```([\s\S]*?)```/g, (_, code) => {
    codeBlocks.push(`<pre><code>${escapeHtml(code.trim())}</code></pre>`);
    return `__CODE_BLOCK_${codeBlocks.length - 1}__`;
  });
  text = text.replace(/`([^`]+)`/g, (_, code) => {
    inlineCodes.push(`<code>${escapeHtml(code)}</code>`);
    return `__INLINE_CODE_${inlineCodes.length - 1}__`;
  });

  text = text.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1" class="rounded-lg" />');
  text = text.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" class="text-accent underline">$1</a>');

  // Keep the document hierarchy: H1 is retained as H1, H2-H4 remain semantic headings.
  text = text.replace(/^#### (.*$)/gim, '<h4>$1</h4>');
  text = text.replace(/^### (.*$)/gim, '<h3>$1</h3>');
  text = text.replace(/^## (.*$)/gim, '<h2>$1</h2>');
  text = text.replace(/^# (.*$)/gim, '<h1>$1</h1>');

  text = text.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  text = text.replace(/__(.*?)__/g, '<strong>$1</strong>');
  text = text.replace(/\*(.*?)\*/g, '<em>$1</em>');
  text = text.replace(/_([^_]+)_/g, '<em>$1</em>');
  text = text.replace(/^>\s?(.*$)/gim, '<blockquote><p>$1</p></blockquote>');

  text = text.replace(/^[-*]\s+(.*)$/gim, '<li>$1</li>');
  text = text.replace(/((?:<li>.*<\/li>\r?\n?)+)/g, '<ul>$1</ul>');
  text = text.replace(/^\d+\.\s+(.*)$/gim, '<oli>$1</oli>');
  text = text.replace(/((?:<oli>.*<\/oli>\r?\n?)+)/g, (match) => `<ol>${match.replaceAll('<oli>', '<li>').replaceAll('</oli>', '</li>')}</ol>`);
  text = text.replace(/^---$/gim, '<hr />');

  text = text.replace(/((?:\|[^\n]+\|\r?\n?)+)/g, (match) => {
    const rawLines = match.trim().split(/\r?\n/).filter((line) => line.trim().startsWith('|'));
    if (rawLines.length < 2 || !/^\|(?:\s*:?-+:?\s*\|)+$/.test(rawLines[1].trim())) return match;
    const parseRow = (line) => line.replace(/^\|/, '').replace(/\|$/, '').split('|').map((cell) => cell.trim());
    const headers = parseRow(rawLines[0]);
    const body = rawLines.slice(2).map((row) => `<tr>${parseRow(row).map((cell) => `<td>${cell}</td>`).join('')}</tr>`).join('');
    return `<table class="border-collapse border border-line w-full text-left my-4"><thead><tr>${headers.map((cell) => `<th>${cell}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table>`;
  });

  const blocks = text.split(/\r?\n\s*\r?\n/);
  const formatted = blocks.map((block) => {
    const trimmed = block.trim();
    if (!trimmed) return '';
    if (/^<(h[1-4]|ul|ol|blockquote|pre|hr|img|table)\b/.test(trimmed) || trimmed.startsWith('__CODE_BLOCK_')) return trimmed;
    return `<p>${trimmed.replace(/\r?\n/g, ' ')}</p>`;
  });

  let html = formatted.filter(Boolean).join('\n');
  html = html.replace(/__INLINE_CODE_(\d+)__/g, (_, idx) => inlineCodes[Number(idx)] || '');
  html = html.replace(/__CODE_BLOCK_(\d+)__/g, (_, idx) => codeBlocks[Number(idx)] || '');
  return addHeadingIds(html, tableOfContents);
}

/** Build the auto-linking dictionary for models, brands and technologies. */
export function buildEntitiesDictionary(models = [], brands = [], locale = 'fr') {
  const prefix = `/${locale}`;
  const entities = [];
  for (const model of models) {
    if (!model.name) continue;
    entities.push({ type: 'model', name: model.name, url: `${prefix}/ecouteurs/${model.id}`, id: model.id });
    const cleaned = model.name.replace(/\s*\([^)]*\)/g, '').trim();
    if (cleaned && cleaned !== model.name && cleaned.length > 3) entities.push({ type: 'model', name: cleaned, url: `${prefix}/ecouteurs/${model.id}`, id: model.id });
  }
  for (const brand of brands) {
    if (brand.name) entities.push({ type: 'brand', name: brand.name, url: `${prefix}/marques/${brand.id}`, id: brand.id });
  }
  const techKeywords = [
    ['Réduction de bruit active', 'anc'], ['Réduction active du bruit', 'anc'], ['Active Noise Cancellation', 'anc'], ['ANC', 'anc'],
    ['Multipoint', 'multipoint'], ['Bluetooth Multipoint', 'multipoint'], ['USB-C', 'usb-c'], ['LDAC', 'codecs/ldac'],
    ['aptX Adaptive', 'codecs/aptx-adaptive'], ['aptX Lossless', 'codecs/aptx-lossless'], ['aptX HD', 'codecs/aptx-hd'], ['aptX', 'codecs/aptx'],
    ['LHDC', 'codecs/lhdc'], ['LC3', 'codecs/lc3'], ['AAC', 'codecs/aac'], ['Bluetooth 5.4', 'bluetooth/5.4'],
    ['Bluetooth 5.3', 'bluetooth/5.3'], ['Bluetooth 5.2', 'bluetooth/5.2'], ['Bluetooth 5.0', 'bluetooth/5.0'],
  ];
  for (const [name, path] of techKeywords) entities.push({ type: 'tech', name, url: `${prefix}/technologies/${path}` });
  const seen = new Set();
  return entities.sort((a, b) => b.name.length - a.name.length).filter((entity) => {
    const key = entity.name.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

/** Auto-link known entities without touching existing links, code or headings. */
export function applyAutoLinking(html, entities = []) {
  if (!html || !entities.length) return { html, stats: { totalLinks: 0, byType: {}, matchedEntities: [] } };
  const matchedSet = new Set();
  const stats = { totalLinks: 0, byType: { model: 0, brand: 0, tech: 0 }, matchedEntities: [] };
  const parts = html.split(/(<a\b[^>]*>[\s\S]*?<\/a>|<pre\b[^>]*>[\s\S]*?<\/pre>|<code\b[^>]*>[\s\S]*?<\/code>|<h[1-6]\b[^>]*>[\s\S]*?<\/h[1-6]>|<[^>]+>)/gi);
  const occurrences = new Map();

  for (let i = 0; i < parts.length; i++) {
    if (parts[i].startsWith('<') || !parts[i].trim()) continue;
    let segment = parts[i];
    for (const entity of entities) {
      const count = occurrences.get(entity.name) || 0;
      if (count >= 2) continue;
      const regex = new RegExp(`(?<![\\p{L}\\p{N}_])(${escapeRegExp(entity.name)})(?![\\p{L}\\p{N}_])`, 'giu');
      segment = segment.replace(regex, (match) => {
        const current = occurrences.get(entity.name) || 0;
        if (current >= 2) return match;
        occurrences.set(entity.name, current + 1);
        stats.totalLinks += 1;
        stats.byType[entity.type] = (stats.byType[entity.type] || 0) + 1;
        if (!matchedSet.has(entity.name)) {
          matchedSet.add(entity.name);
          stats.matchedEntities.push({ name: entity.name, type: entity.type, url: entity.url });
        }
        return `<a href="${entity.url}" class="text-accent underline">${match}</a>`;
      });
    }
    parts[i] = segment;
  }
  return { html: parts.join(''), stats };
}

/** Parse a complete Markdown article for the admin importer. */
export function parseArticleMarkdown(mdContent, { models = [], brands = [], locale = 'fr', autoLink = true } = {}) {
  if (!mdContent || typeof mdContent !== 'string') return null;
  const { data: frontmatter, body } = parseFrontmatter(mdContent);
  let title = frontmatter.title || '';
  let excerpt = frontmatter.excerpt || '';
  const status = frontmatter.status === 'published' ? 'published' : 'draft';
  const detectedLocale = frontmatter.locale || locale;
  let id = frontmatter.id || frontmatter.slug || '';
  const cover_image_url = frontmatter.cover_image_url || frontmatter.cover_image || null;
  const translation_of = frontmatter.translation_of || null;
  let cleanBody = body;

  if (!title) {
    const titleMatch = cleanBody.match(/^#\s+(.*)$/m) || cleanBody.match(/^##\s+(.*)$/m);
    if (titleMatch) {
      title = titleMatch[1].trim();
      cleanBody = cleanBody.replace(titleMatch[0], '').trim();
    }
  }
  if (!id && title) id = slugify(title);

  if (!excerpt) {
    for (const paragraph of cleanBody.split(/\r?\n\s*\r?\n/)) {
      const trimmed = paragraph.trim();
      if (trimmed && !trimmed.startsWith('#') && !trimmed.startsWith('>') && !trimmed.startsWith('![')) {
        excerpt = trimmed.replace(/[*_`#]/g, '').slice(0, 250).trim();
        if (trimmed.length > 250) excerpt += '…';
        break;
      }
    }
  }

  const tableOfContents = extractTableOfContents(cleanBody);
  let content_html = markdownToHtml(cleanBody, tableOfContents);
  let linkingStats = { totalLinks: 0, byType: {}, matchedEntities: [] };
  if (autoLink && (models.length || brands.length)) {
    const result = applyAutoLinking(content_html, buildEntitiesDictionary(models, brands, detectedLocale));
    content_html = result.html;
    linkingStats = result.stats;
  }

  const plainText = cleanBody
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/\[[^\]]+\]\([^)]*\)/g, '$1')
    .replace(/[#>*_`|]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  const word_count = plainText ? plainText.split(/\s+/).length : 0;
  const reading_minutes = Math.max(1, Math.ceil(word_count / 220));

  return {
    title,
    excerpt,
    id,
    status,
    locale: detectedLocale,
    cover_image_url,
    translation_of,
    content_html,
    table_of_contents: tableOfContents,
    word_count,
    reading_minutes,
    linkingStats,
  };
}
